"""
================================================================================
MEMORY SERVICE - SESSION-BASED CHAT HISTORY MANAGEMENT
================================================================================

This module manages conversation history for the Smart Manufacturing Assistant.

WHAT IT DOES:
- Stores chat messages (user and AI) per session.
- Provides formatted history for LLM context.
- Supports multiple concurrent chat sessions.
- Allows clearing history for privacy/reset.

WHY LANGCHAIN ChatMessageHistory?
- **Standard Interface**: Well-known API across AI frameworks.
- **Message Types**: Distinguishes between Human and AI messages.
- **Extensible**: Can swap to Redis, PostgreSQL, or file storage if needed.
- **Lightweight**: In-memory storage for fast access.

HOW IT WORKS:
1. Each session has a unique ID (generated by frontend).
2. Messages are stored in a ChatMessageHistory object per session.
3. History is formatted as text for LLM prompts.
4. Memory enables context-aware conversations ("What did I ask earlier?").

CURRENT IMPLEMENTATION:
- In-memory storage (data lost on server restart).
- For production, consider persistent storage (Redis, database).

BIG PICTURE:
- Enables multi-turn conversations with context.
- Used by the Orchestrator to include history in prompts.
- Essential for follow-up questions and context retention.

ARCHITECTURE:
    [Chat API]
         |
         | save user message
         v
    [Memory Service]  <-- YOU ARE HERE
         |
         | get formatted history
         v
    [Orchestrator] --> [LLM Prompt with History]
================================================================================
"""

from typing import Dict, List
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage


class MemoryService:
    """
    Service for managing session-based chat history using LangChain.
    
    Uses a dictionary to store separate ChatMessageHistory objects for each
    session, enabling multiple concurrent user conversations.
    
    Attributes:
        _sessions: Dictionary mapping session_id to ChatMessageHistory.
    """
    
    def __init__(self):
        """
        Initialize the memory service with an empty sessions dictionary.
        """
        # Dictionary to store ChatMessageHistory per session
        # Key: session_id (str), Value: ChatMessageHistory instance
        self._sessions: Dict[str, ChatMessageHistory] = {}

    def get_session_history(self, session_id: str) -> ChatMessageHistory:
        """
        Get or create a ChatMessageHistory for the given session.
        
        WHAT: Returns the history object for a session, creating if needed.
        HOW: Checks if session exists in dict, creates new if not.
        BIG PICTURE: Ensures every session has its own isolated history.
        
        Args:
            session_id: Unique identifier for the chat session.
            
        Returns:
            ChatMessageHistory: The history object for this session.
        """
        if session_id not in self._sessions:
            # Create new history for first-time sessions
            self._sessions[session_id] = ChatMessageHistory()
        return self._sessions[session_id]

    def add_user_message(self, session_id: str, message: str):
        """
        Add a user message to the session history.
        
        WHAT: Records what the user said.
        HOW: Gets session history and appends a HumanMessage.
        BIG PICTURE: Called by Orchestrator before processing each request.
        
        Args:
            session_id: The session to add the message to.
            message: The user's message text.
        """
        history = self.get_session_history(session_id)
        history.add_user_message(message)

    def add_ai_message(self, session_id: str, message: str):
        """
        Add an AI response to the session history.
        
        WHAT: Records what the AI responded.
        HOW: Gets session history and appends an AIMessage.
        BIG PICTURE: Called by Orchestrator after generating each response.
        
        Args:
            session_id: The session to add the message to.
            message: The AI's response text.
        """
        history = self.get_session_history(session_id)
        history.add_ai_message(message)

    def get_formatted_history(self, session_id: str) -> str:
        """
        Get the chat history formatted as a string for LLM prompts.
        
        WHAT: Converts message objects to a readable text format.
        HOW: Iterates through messages, prefixing with "User:" or "AI:".
        BIG PICTURE: This string is injected into LLM prompts for context.
        
        Args:
            session_id: The session to get history for.
            
        Returns:
            str: Formatted history like "User: Hello\nAI: Hi there!\n..."
        """
        history = self.get_session_history(session_id)
        messages = history.messages
        formatted_history = ""
        
        for msg in messages:
            if isinstance(msg, HumanMessage):
                formatted_history += f"User: {msg.content}\n"
            elif isinstance(msg, AIMessage):
                formatted_history += f"AI: {msg.content}\n"
                
        return formatted_history

    def clear_history(self, session_id: str):
        """
        Clear all messages from a session's history.
        
        WHAT: Removes all messages from the specified session.
        HOW: Calls clear() on the ChatMessageHistory if it exists.
        BIG PICTURE: Used when user clicks "Clear History" button.
        
        Args:
            session_id: The session to clear.
        """
        if session_id in self._sessions:
            self._sessions[session_id].clear()

    def get_all_sessions(self) -> List[str]:
        """
        Get a list of all active session IDs.
        
        WHAT: Returns all session IDs that have history.
        HOW: Returns keys of the sessions dictionary.
        BIG PICTURE: Used by frontend to show session dropdown.
        
        Returns:
            List[str]: List of session ID strings.
        """
        return list(self._sessions.keys())

    def get_messages(self, session_id: str) -> List[Dict[str, str]]:
        """
        Get messages in a format suitable for the frontend.
        
        WHAT: Returns messages as a list of dicts with role and content.
        HOW: Converts LangChain message objects to simpler dict format.
        BIG PICTURE: Used by GET /chat/history endpoint for frontend display.
        
        Args:
            session_id: The session to get messages for.
            
        Returns:
            List[Dict]: Messages like [{"role": "user", "content": "..."}]
        """
        history = self.get_session_history(session_id)
        messages = []
        
        for msg in history.messages:
            role = "user" if isinstance(msg, HumanMessage) else "assistant"
            messages.append({"role": role, "content": msg.content})
            
        return messages


# Global singleton instance
# Shared across all API requests to maintain state
memory_service = MemoryService()

